### ISSUE TITLE
Unable to purchase second kettle

### ISSUE THREAD

**Issue by ThorinMF** [jhaakma/ashfall#10]
Hi, I'm unable to purchase a second kettle. I own a steel kettle that I have set up on a campfire in Ald-ruhn but I want to have one kettle set up permanently and one for traveling with, and I've tried repeatedly from both Arrille and Ra'virr to purchase an iron kettle and it takes my gold but doesn't put the kettle in my inventory.
[MWSE.log](https://github.com/jhaakma/ashfall/files/6912865/MWSE.log)

**Comment by jhaakma** [comment]
Fixed in version 2.2.1
