### ISSUE TITLE
Unable to use bedrolls or wateractivators

### ISSUE THREAD

**Issue by for4ks** [jhaakma/ashfall#21]
Hello, I'm unable to use either my bedrolls (I just immediately pick them back up) or any water sources. I tried after updating to most recent versions of CF and Ashfall, and updating mwse before starting a new game.
[MWSE.log](https://github.com/jhaakma/ashfall/files/10866660/MWSE.log)

**Comment by jhaakma** [comment]
Looks like your mods and mwse haven't updated properly. The error is coming from a file that no longer exists in Crafting Framework (it was moved to another folder), and it's failing because it's missing the logger:assert function which was added to MWSE recently.

Are you using MO2 by chance?

**Comment by for4ks** [comment]
I am, indeed. I recently tried simply downloading the nightly zip for mwse, too. No luck.

**Comment by jhaakma** [comment]
Can you delete you MWSE/mods/CraftingFramework folder and reinstall Crafting Framework. Then check that there is no MWSE related stuff in your MO2 overrides folder and clear out any you find. Then delete your Morrowind/mwse-version.txt file and try runn MWSE-update.exe again, and try replicate the issue and send your logs again. Thanks

**Comment by for4ks** [comment]
Ok, here is the new log.
[MWSE.log](https://github.com/jhaakma/ashfall/files/10878047/MWSE.log)

**Comment by jhaakma** [comment]
Yeah, something is very wrong with your MWSE install, it says it's the latest version but it definitely isn't. 

This is a bit beyond my area of expertise, I suggest you visit NullCascade in the #mwse channel in the modding discord and ask him to help you update it properly: https://discord.gg/3JJTpWKvdK

**Comment by for4ks** [comment]
After some more tooling around I think I was able to find the problem: since I have to run mge xe through mo, there was still a very old mwse folder located in the folder I set my mge outputs to dump to. Deleting that  seems to have fixed things. Thank you for the help, regardless.
