### ISSUE TITLE
Campfire Interaction Crash

### ISSUE THREAD

**Issue by Starblast16** [jhaakma/ashfall#26]
As stated above, sometimes when I try to interact with a campfire, like add a utensil or add firewood, the game crashes. I've attached the MWSE.log.
[MWSE.log](https://github.com/jhaakma/ashfall/files/12835325/MWSE.log)
Had to put the MiniDump file into an archive to upload it.
[MWSE_MiniDump.zip](https://github.com/jhaakma/ashfall/files/12835336/MWSE_MiniDump.zip)

**Comment by jhaakma** [comment]
This has been fixed in the latest version of MWSE. Run MWSE-Update.exe and let me know if you still have issues. Thanks!
