### ISSUE TITLE
Fish rack crash

### ISSUE THREAD

**Issue by Goerid** [jhaakma/ashfall#27]
Every time I try to interact with the fish rack the game crashes, after I ran the last update for MWSE.
[MWSE.log](https://github.com/jhaakma/ashfall/files/13079592/MWSE.log)
[MWSE_MiniDump.dmp](https://github.com/jhaakma/ashfall/files/13079598/MWSE_MiniDump.dmp)

**Comment by jhaakma** [comment]
Thanks. This was caused by a missing texture. I'll fix this later today, but if you want to fix the crash now, installing [OAAB Data](https://www.nexusmods.com/morrowind/mods/49042) should do the trick.

**Comment by Goerid** [comment]
OK I'll give it a try. I honestly didn't expect you to answer this quickly, thank you

Edit: installed OAAB Data, everything seems to be working fine now.

**Comment by jhaakma** [comment]
Nice, thanks for reporting the issue!
