### ISSUE TITLE
Ashfall conflict with Windoors glow

### ISSUE THREAD

**Issue by cetyree** [jhaakma/ashfall#4]
Hi Merlord,

Thank you for your time and your awesome mods for MW.

I was hoping you could help resolve a conflict I am having:

I use GITD (https://www.nexusmods.com/morrowind/mods/45886) by Melchior Dahrk, and use the included "RR_Windoors_Glow_1C.esp" from that mod, which applies day / night  effects to shacks, yurts, and under doors. 
When run with Ashfall, the campfires in the shacks and yurts appear incorrectly positioned, kind of buried in the ground, or appear incomplete.

Not sure if many people use the Windoors glow mod, but I like the effects. I am sure it is something in that mod that causes the conflict, but am a novice concerning modding, or could be something I am doing wrong. 

Thanks again for your time.

Updated to latest MWSE version, and confirmed the requirements.
I turned off all mods except below listed, and started a new game. I have a couple of screenshots attached here, along with the MWSE log, and the windoors ESP file. 

Active Mods:
001  Morrowind.esm
002  Tribunal.esm
003  Bloodmoon.esm
004  RR_Windoors_Glow_1C.esp
005  Ashfall.esp

![Screenshot 2021-04-12 21 40 10 392](https://user-images.githubusercontent.com/80136771/114485867-ac404100-9bda-11eb-9023-954666acaa57.jpg)
![Screenshot 2021-04-12 21 47 51 224](https://user-images.githubusercontent.com/80136771/114485870-ac404100-9bda-11eb-8588-f76feecec3e8.jpg)
[MWSE.log](https://github.com/jhaakma/ashfall/files/6300757/MWSE.log)
[RR_Windoors_Glow_1C.zip](https://github.com/jhaakma/ashfall/files/6300759/RR_Windoors_Glow_1C.zip)

**Comment by jhaakma** [comment]
Does the problem occur if you start a new game with windoors and enter a shack? Or only on existing games where the Ashfall campfires have already been placed?

**Comment by cetyree** [comment]
Hi Merlord,

The problem occurs with start new game, active load order above, and enter a shack. 

Also, as a quick test I started a new game without the Windoors activated, then saved game. Then activated Windoors, and reloaded game. This also caused same issue, if that helps any.

Thanks again for your help.

**Comment by cetyree** [comment]
Hi Merlord,

Thank you for any time or effort spent looking at this. I am closing the issue, as it was just a matter of editing the yurt and shack  meshes to work with GITD, as was clearly detailed in the GITD documentation. I apologize for wasting your time. Still learning . . . . . .

**Comment by jhaakma** [comment]
No worries, glad you got it sorted!
