### ISSUE TITLE
Ashfall: Heat from disabled interop sources

### ISSUE THREAD

**Issue by B00ze64** [jhaakma/ashfall#6]
Good day.

It seems disabled interop heat sources are still counted on the player. In Mudcrab Island, there is a ship that gets attacked/boarded by another ship. That other ship eventually catches fire. This is controlled by disabling/enabling the fires (Lights). But I get hot as soon as the pirate ship shows-up, even if it's not on fire, so long as I am close enough to where the fire (disabled) is located...

Regards,

**Comment by B00ze64** [comment]
I think you've fixed this with b67e36f, I haven't tested, just looked at the commit, thanks!

**Comment by jhaakma** [comment]
Fixed in v2.2.0
