### ISSUE TITLE
Support Better Names Clothing

### ISSUE THREAD

**Issue by B00ze64** [jhaakma/ashfall#8]
Good day Merlord.

Please edit the following in ratingsConfig.lua to support "Better Sorting Names" mod. The armors are OK (you could add CLOTH with low heat for the few cheap pieces of that) but the clothing all gets renamed with quality last (Common Pants -> Pants Common) so the clothing table could be changed to:
```lua
    clothing = {
        default = 60,
        enchanted = 80,
        values = {
            ['common '] = 40,
            ['expensive '] = 50,
            ['extravagant '] = 60,
            ['exquisite '] = 70,
            [' common'] = 40,
            [' expensive'] = 50,
            [' extravagant'] = 60,
            [' exquisite'] = 70,
            ['fire'] = 100,
            ['flame'] = 100,
            ['frost'] = 0
        }
    },
```
Thank you.

**Comment by jhaakma** [comment]
Added in v2.2.3
