### ISSUE TITLE
CTD after pressing spacebar

### ISSUE THREAD

**Issue by Landro2340** [jhaakma/ashfall#9]
Hello, I have the following issue. I installed the mod and booted a new game, after pressing the spacebar the game just crashes. The problem can also occur if I press the spacebar on the main menu without even starting a game, for reference I do have the latest versions of MWSE and MGE.
[MWSE.log](https://github.com/jhaakma/ashfall/files/6912157/MWSE.log)
And apparently the .DMP minidump file cannot be uploaded through github :(, any help is appreciated! This mod looks great!

**Comment by jhaakma** [comment]
tes3.getCameraVector() seems to be crashing from the main menu. I can't replicate the issue myself but I can easily add a check to stop that code running from the main menu.

**Comment by jhaakma** [comment]
Should be fixed in v2.2.3
